[package]
name = "torbox-rs"
version = "0.0.1-alpha.1"
edition = "2024"
description = "Rust SDK for the torbox API"
license = "MIT"

[features]
default = []
specta = ["dep:specta"]

[dependencies]
specta = { version = "2.0.0-rc.22", optional = true, features = [
    "serde",
    "serde_json",
    "derive",
] }

[workspace]
members = [
    "local-crates/torbox-core-rs",
    "local-crates/torbox-ddl-rs",
    "local-crates/torbox-torrent-rs",
]

[workspace.dependencies]
reqwest = "0.12.20"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
