[package]
name = "torbox-rs"
version = "0.0.1-alpha.1"
edition = "2024"
description = "Rust SDK for the torbox API"
license = "MIT"
authors = ["CarrotRub"]
repository = "https://github.com/CarrotRub/torbox-rs"
homepage = "https://github.com/CarrotRub/torbox-rs"
keywords = ["sdk", "development-tools"]

[features]
default = []
specta = ["dep:specta", "torbox-core-rs/specta"]

[dependencies]
specta = { version = "2.0.0-rc.22", optional = true, features = [
    "serde",
    "serde_json",
    "derive",
] }
torbox-core-rs = { path = "local-crates/torbox-core-rs", features = [
    "specta",
], version = "0.0.1-alpha.1" }


[workspace]
members = [
    "local-crates/torbox-core-rs",
    "local-crates/torbox-ddl-rs",
    "local-crates/torbox-torrent-rs",
]

[workspace.dependencies]
reqwest = "0.12.20"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
