[package]
name = "torbox-core-rs"
version = "0.0.1-alpha.1"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true }
specta = { version = "2.0.0-rc.22", optional = true, features = [
    "serde",
    "serde_json",
    "derive",
] }
